### ISSUE TITLE
Feature Request:  Select compression level

### ISSUE THREAD

**Issue by rbarrott** [eslam-gomaa/virt-backup#2]
It could be useful to have the compression level as a command-line option.
The use-case is that the user can trade speed of the backup against disk space.
For example, I may want faster backups and am happy to sacrifice disk space for this.

E.g.:  $ ruby virt-backup.rb --backup --original-vm MyVM --with-snapshots --save-dir ~/vmbackups --compression none

Valid options for --compression could be:
    none
    fastest
    smallest
    default

These correspond to the appropriate Zip compression options.
If --compression is not provided, the default value of "default" is used.

**Comment by eslam-gomaa** [comment]
Hello,

Support for choosing compression level  has been added

Note: the library only supports 3 levels of compression: 
```
Possible values are Zlib::BEST_COMPRESSION, Zlib::DEFAULT_COMPRESSION and Zlib::NO_COMPRESSION
```

---

## Example

* Backup without compression

> supported  (--compression) values are:  default, none, best

```bash
ruby virt-backup.rb --backup \
 --with-snapshots \
 --original-vm kubernetes-master \
 --system-disk-only \
 --compression none
 --save-dir /var/lib/libvirt/images/backup/
```

**Comment by eslam-gomaa** [comment]
Feature added,  Closing the issue.
