### ISSUE TITLE
error in disk backup

### ISSUE THREAD

**Issue by andreasc87** [eslam-gomaa/virt-backup#3]
I have little to no experience with ruby, I just found your project to be exactly what I needed - Thank you 👍 

I did however have some issues when trying to do a VM backup.

OS: Newly installed and fully updated Ubuntu 20.04 LTS server

I executed with the following command:

****
sudo ruby virt-backup.rb --backup \
 --with-snapshots \
 --original-vm win2k19 \
 --compression best \
 --save-dir /mnt/usbdisk/win2k19_Saturday/
****

I got the following output:

****
[ Warning ] (1) Missing disk/s found, Will NOT be backed up:
             => ["/var/lib/libvirt/images/win2k19.qcow2' index='1"]

[ INFO ] Current VM State: running
[ INFO ] Pausing the VM
[ INFO ] Getting checksum of the Files will be backed up - May take time based on size
[ INFO ] Backing up VM: (win2k19), N of disks: (0) - May take time based on size
          => win2k19.checksum  [OK]
          => win2k19.xml  [OK]
[ INFO ] Resuming the VM
[ INFO ] Current VM State: running
[ INFO ] Backup stored successfully in (/mnt/usbdisk/win2k19_Saturday/win2k19.zip)
****

For the fixing I added:
 STDERR.puts File.readlines(xml.path).grep(/source file=/).collect {|disk| disk.strip.gsub(/source file=/, '').gsub(/<'/,'').gsub("'/>", '')}
to line 100 in functions.rb

This line also output "/var/lib/libvirt/images/win2k19.qcow2' index='1" without the ""

I the edited line 98 to to remove the stuff I did not want in there, which made it look like this:
info[:disks] = File.readlines(xml.path).grep(/source file=/).collect {|disk| disk.strip.gsub(/<source file=/, '').gsub(/\/>/, '').gsub("'", '').gsub(/ index=1/, '')}

I know it is not pretty. Not even correct by any standards, but as I have never before today looked at a ruby script, I think it went alright.
A proper ruby programmer like yourself could probablt easily figure out what went wrong.

Also, the first thing I tested was that the qcow2 file was infact where it looked for it, and it was.

the XML file for the VM in question

***

<domain type='kvm'>
  <name>win2k19</name>
  <uuid>13ce54b2-cf58-4f10-8c99-0e79b2fafe05</uuid>
  <metadata>
    <libosinfo:libosinfo xmlns:libosinfo="http://libosinfo.org/xmlns/libvirt/domain/1.0">
      <libosinfo:os id="http://microsoft.com/win/2k19"/>
    </libosinfo:libosinfo>
  </metadata>
  <memory unit='KiB'>8388608</memory>
  <currentMemory unit='KiB'>8388608</currentMemory>
  <vcpu placement='static'>16</vcpu>
  <os>
    <type arch='x86_64' machine='pc-q35-4.2'>hvm</type>
    <boot dev='hd'/>
  </os>
  <features>
    <acpi/>
    <apic/>
    <hyperv>
      <relaxed state='on'/>
      <vapic state='on'/>
      <spinlocks state='on' retries='8191'/>
    </hyperv>
    <vmport state='off'/>
  </features>
  <cpu mode='host-model' check='partial'/>
  <clock offset='localtime'>
    <timer name='rtc' tickpolicy='catchup'/>
    <timer name='pit' tickpolicy='delay'/>
    <timer name='hpet' present='no'/>
    <timer name='hypervclock' present='yes'/>
  </clock>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>destroy</on_crash>
  <pm>
    <suspend-to-mem enabled='no'/>
    <suspend-to-disk enabled='no'/>
  </pm>
  <devices>
    <emulator>/usr/bin/qemu-system-x86_64</emulator>
    <disk type='file' device='disk'>
      <driver name='qemu' type='qcow2'/>
      <source file='/var/lib/libvirt/images/win2k19.qcow2'/>
      <target dev='sda' bus='sata'/>
      <address type='drive' controller='0' bus='0' target='0' unit='0'/>
    </disk>
    <controller type='usb' index='0' model='qemu-xhci' ports='15'>
      <address type='pci' domain='0x0000' bus='0x02' slot='0x00' function='0x0'/>
    </controller>
    <controller type='sata' index='0'>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x1f' function='0x2'/>
    </controller>
    <controller type='pci' index='0' model='pcie-root'/>
    <controller type='pci' index='1' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='1' port='0x10'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x0' multifunction='on'/>
    </controller>
    <controller type='pci' index='2' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='2' port='0x11'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x1'/>
    </controller>
    <controller type='pci' index='3' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='3' port='0x12'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x2'/>
    </controller>
    <controller type='pci' index='4' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='4' port='0x13'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x3'/>
    </controller>
    <controller type='pci' index='5' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='5' port='0x14'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x4'/>
    </controller>
    <controller type='virtio-serial' index='0'>
      <address type='pci' domain='0x0000' bus='0x03' slot='0x00' function='0x0'/>
    </controller>
    <interface type='bridge'>
      <mac address='52:54:00:2b:4f:b5'/>
      <source bridge='br0'/>
      <model type='e1000e'/>
      <address type='pci' domain='0x0000' bus='0x01' slot='0x00' function='0x0'/>
    </interface>
    <serial type='pty'>
      <target type='isa-serial' port='0'>
        <model name='isa-serial'/>
      </target>
    </serial>
    <console type='pty'>
      <target type='serial' port='0'/>
    </console>
    <channel type='spicevmc'>
      <target type='virtio' name='com.redhat.spice.0'/>
      <address type='virtio-serial' controller='0' bus='0' port='1'/>
    </channel>
    <input type='tablet' bus='usb'>
      <address type='usb' bus='0' port='1'/>
    </input>
    <input type='mouse' bus='ps2'/>
    <input type='keyboard' bus='ps2'/>
    <graphics type='spice' autoport='yes'>
      <listen type='address'/>
      <image compression='off'/>
    </graphics>
    <graphics type='vnc' port='-1' autoport='yes'>
      <listen type='address'/>
    </graphics>
    <sound model='ich9'>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x1b' function='0x0'/>
    </sound>
    <video>
      <model type='qxl' ram='65536' vram='65536' vgamem='16384' heads='1' primary='yes'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x01' function='0x0'/>
    </video>
    <redirdev bus='usb' type='spicevmc'>
      <address type='usb' bus='0' port='2'/>
    </redirdev>
    <redirdev bus='usb' type='spicevmc'>
      <address type='usb' bus='0' port='3'/>
    </redirdev>
    <memballoon model='virtio'>
      <address type='pci' domain='0x0000' bus='0x04' slot='0x00' function='0x0'/>
    </memballoon>
  </devices>
</domain>
***

**Comment by andreasc87** [comment]
apparently it clipped the XML file. I will add it here as an attached file.
[win2k19.xml.txt](https://github.com/eslam-gomaa/virt-backup/files/5578360/win2k19.xml.txt)

**Comment by eslam-gomaa** [comment]
Hello Andrea,

Thank you for letting me know

To give you a simple reply: the problem is *somehow the following block in the XML had an extra String 'inxex=1'* for example `<source file='/var/lib/libvirt/images/win2k19.qcow2 index=1'/>`
```xml
    <disk type='file' device='disk'>
      <driver name='qemu' type='qcow2'/>
      <source file='/var/lib/libvirt/images/win2k19.qcow2'/>
      <target dev='sda' bus='sata'/>
      <address type='drive' controller='0' bus='0' target='0' unit='0'/>
    </disk>
```

Not sure how, because it does not exist in the XML you've attached,  also I've defined your XML on a test machine and the backup worked normally.

---

Anyway, it's not a problem

I modified line `98` ,  It's very close your modifications but matches any index number (there is no problem if the index part does not exist)
```ruby
info[:disks] = File.readlines(xml.path).grep(/source file=/).collect {|disk| disk.strip.gsub(/source file=/, '').gsub(/<'/,'').gsub("'/>", '').gsub(/index=[0-9]+/, '')}
```

---

I'd like to thank you again, and please feed me back after your test


Eslam

**Comment by andreasc87** [comment]
I swapped out the line I edited with the one you have now made, and that set me back to generating this error:
[ Warning ] (1) Missing disk/s found, Will NOT be backed up:
             => ["/var/lib/libvirt/images/win2k19.qcow2' index='1"]

[ INFO ] Current VM State: running
[ INFO ] Pausing the VM
[ INFO ] Getting checksum of the Files will be backed up - May take time based on size
[ INFO ] Backing up VM: (win2k19), N of disks: (0) - May take time based on size
          => win2k19.checksum  [OK]
          => win2k19.xml  [OK]
[ INFO ] Resuming the VM
[ INFO ] Current VM State: running
[ INFO ] Backup stored successfully in (/mnt/usbdisk/win2k19_Sunday/win2k19.zip)


I have double checked that the XML i posted here is infact the correct one. There is no mentions of index=1 or anything else in said line.

**Comment by eslam-gomaa** [comment]
So, if that `.gsub(/ index=1/, '')` fixed your issue,  may u try `.gsub(/ index=[0-9]+/, '')` ?

**Comment by andreasc87** [comment]
give me a second.

**Comment by andreasc87** [comment]
Still generating the same error. that made no changes

**Comment by andreasc87** [comment]
I _can_ use the index=[0-9]+ part. I've replaced my / index=1/ with / index=[0-9]+ and that worked, making the complete line looking like so:
info[:disks] = File.readlines(xml.path).grep(/source file=/).collect {|disk| disk.strip.gsub(/<source file=/, '').gsub(/\/>/, '').gsub("'", '').gsub(/ index=[0-9]+/, '')}

**Comment by andreasc87** [comment]
(perhaps that was what you wanted to me try all along? ) :)

**Comment by eslam-gomaa** [comment]
Actually, that's what I wanted to test :)

Glad that it worked, Thanks a lot

**Comment by andreasc87** [comment]
Excellent & you're welcome.
 Thanks for spending the time. Have a good day.
